#!/usr/bin/env python3
"""Regenerate the web UI's icons from the iOS app icon.

    python3 tools/web/make-icon.py            # needs Pillow

Inputs and outputs, all relative to the repository root:

    tools/web/icon-master-512.png          the iOS AppIcon (app_icon_1024.png), downscaled to 512 px
    crates/aulos-api/web/icon-180.png      180 px, 128-colour palette — Apple touch icon, Safari
                                           favicon and the header mark (`.mark` in app.css)
    crates/aulos-api/web/icon.svg          the 128 px raster base64-embedded in an SVG and clipped
                                           to the iOS corner radius — the favicon for Chrome/Firefox

Both outputs are palette PNGs: the artwork's grainy background does not compress as truecolour,
and a favicon that weighs 70 KB is a favicon that is fetched on every cold tab. The budgets below
keep the two files where the old placeholder mark was, within a few KB.

The touch icon is full-bleed on purpose: iOS masks it to its own rounded square, so a rounded or
transparent corner here would only ever show up as a black notch.
"""

from __future__ import annotations

import base64
import pathlib

try:
    from PIL import Image
except ImportError as e:  # pragma: no cover - a tooling script
    raise SystemExit("make-icon.py needs Pillow: pip install pillow") from e

ROOT = pathlib.Path(__file__).resolve().parents[2]
MASTER = ROOT / "tools/web/icon-master-512.png"
PNG_OUT = ROOT / "crates/aulos-api/web/icon-180.png"
SVG_OUT = ROOT / "crates/aulos-api/web/icon.svg"

PNG_BUDGET = 24_000
SVG_BUDGET = 16_000
CORNER = 40  # the iOS corner radius on a 180 px canvas, as the old mark used


def raster(src: Image.Image, size: int, colours: int) -> bytes:
    im = src.resize((size, size), Image.LANCZOS)
    im = im.quantize(colours, method=Image.Quantize.MEDIANCUT, dither=Image.Dither.FLOYDSTEINBERG)
    import io

    out = io.BytesIO()
    im.save(out, "PNG", optimize=True)
    return out.getvalue()


def main() -> None:
    src = Image.open(MASTER).convert("RGB")
    if src.size != (512, 512):
        raise SystemExit(f"{MASTER} must be 512x512, got {src.size}")

    png = raster(src, 180, 128)
    PNG_OUT.write_bytes(png)
    print(f"{PNG_OUT} — {len(png)} bytes")
    if len(png) > PNG_BUDGET:
        raise SystemExit(f"icon-180.png must stay under {PNG_BUDGET} bytes")

    embedded = base64.b64encode(raster(src, 128, 96)).decode("ascii")
    svg = (
        '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" '
        'viewBox="0 0 180 180" width="180" height="180" role="img" aria-label="Aulos">\n'
        "  <!-- The iOS app icon (tools/web/icon-master-512.png), rasterised at 128 px and clipped to the\n"
        "       iOS corner radius. Generated by tools/web/make-icon.py; do not edit by hand. -->\n"
        f'  <clipPath id="r"><rect width="180" height="180" rx="{CORNER}" ry="{CORNER}"/></clipPath>\n'
        f'  <image width="180" height="180" clip-path="url(#r)" xlink:href="data:image/png;base64,{embedded}"/>\n'
        "</svg>\n"
    )
    SVG_OUT.write_text(svg)
    print(f"{SVG_OUT} — {len(svg)} bytes")
    if len(svg) > SVG_BUDGET:
        raise SystemExit(f"icon.svg must stay under {SVG_BUDGET} bytes")


if __name__ == "__main__":
    main()
