//! The optional real-yt-dlp smoke: a `file://` extract **and** download of a one-second clip
//! generated by `ffmpeg` at test time.
//!
//! Network-free by construction — the URL is a local file — but it needs a real `yt_dlp` and a
//! real `ffmpeg`, neither of which the CI `test` job installs. Both are probed and the tests
//! **skip** rather than fail when they are absent, because PLAN WP-07 says the suite must not
//! depend on them. Point `AULOS_TEST_PYTHON` at an interpreter that has yt-dlp to run them:
//!
//! ```text
//! AULOS_TEST_PYTHON=~/Development/metube_pot/.venv/bin/python \
//!   cargo test -p aulos-provider-ytdlp --test real_ytdlp
//! ```
//!
//! Inside the image both are present, so this is the "a real download works end to end through
//! the shim" half of the definition of done, one layer below the yt-dlp-nightly smoke of
//! DESIGN §18.5.

#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::path::PathBuf;
use std::process::{Command, Stdio};
use std::time::Duration;

use aulos_core::id::ItemId;
use aulos_provider::entry::EntryKind;
use aulos_provider::sink::{ProgressMsg, ProgressSink, ProgressSinkFactory, Stage};
use aulos_provider_ytdlp::job::{ExtractOpts, Job, Policy};
use aulos_provider_ytdlp::runner::{RunnerHandle, RunnerOutcome};
use serde_json::json;
use tempfile::TempDir;
use tokio::sync::mpsc;
use tokio_util::sync::CancellationToken;
use url::Url;

fn shim() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("python/ytdlp_runner.py")
}

fn python() -> String {
    std::env::var("AULOS_TEST_PYTHON").unwrap_or_else(|_| "python3".to_owned())
}

/// Whether the chosen interpreter can import yt-dlp.
fn have_ytdlp() -> bool {
    Command::new(python())
        .arg("-c")
        .arg("import yt_dlp")
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .is_ok_and(|s| s.success())
}

fn have(tool: &str) -> bool {
    Command::new(tool)
        .arg("-version")
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .is_ok_and(|s| s.success())
}

macro_rules! skip_unless_real {
    () => {
        if !have_ytdlp() {
            eprintln!("skipping: {} cannot import yt_dlp", python());
            return;
        }
        if !have("ffmpeg") {
            eprintln!("skipping: no ffmpeg on PATH");
            return;
        }
    };
}

/// A one-second H.264 + AAC clip, generated on the spot.
///
/// Generated rather than checked in so the repository carries no binary blob, and so the clip is
/// always something the local ffmpeg can actually produce.
fn make_clip(dir: &TempDir) -> PathBuf {
    let path = dir.path().join("clip.mp4");
    let status = Command::new("ffmpeg")
        .args([
            "-y",
            "-f",
            "lavfi",
            "-i",
            "testsrc=duration=1:size=160x120:rate=10",
            "-f",
            "lavfi",
            "-i",
            "sine=frequency=440:duration=1",
            "-c:v",
            "libx264",
            "-preset",
            "ultrafast",
            "-c:a",
            "aac",
            "-shortest",
            "-loglevel",
            "error",
        ])
        .arg(&path)
        .status()
        .expect("ffmpeg must be runnable");
    assert!(status.success(), "ffmpeg failed to build the fixture clip");
    assert!(path.exists());
    path
}

fn handle() -> RunnerHandle {
    RunnerHandle::new(python(), shim())
        .with_kill_grace(Duration::from_millis(500))
        .with_stall(None)
        .with_timeout(Some(Duration::from_secs(120)))
}

fn sink() -> (ProgressSink, mpsc::Receiver<ProgressMsg>) {
    let (factory, rx) = ProgressSinkFactory::channel();
    (factory.for_item(ItemId::new()), rx)
}

/// yt-dlp refuses `file://` unless asked; the *request* opts it in, not the shim.
fn file_url_options() -> serde_json::Map<String, serde_json::Value> {
    let mut options = serde_json::Map::new();
    options.insert("enable_file_urls".to_owned(), json!(true));
    options.insert("no_color".to_owned(), json!(true));
    options
}

#[tokio::test]
async fn a_real_file_url_extract_yields_one_video_entry() {
    skip_unless_real!();
    let dir = TempDir::new().unwrap();
    let clip = make_clip(&dir);
    let url = Url::from_file_path(&clip).expect("a file url");

    let job = Job::extract(ItemId::new().to_string(), url.clone())
        .with_options(file_url_options())
        .with_extract(ExtractOpts::default());
    let (sink, _rx) = sink();
    let RunnerOutcome::Extracted { entries, truncated } = handle()
        .run(&job, &sink, &CancellationToken::new())
        .await
        .expect("a real extract of a local file must succeed")
    else {
        panic!("expected an extraction")
    };

    assert!(!truncated);
    assert_eq!(entries.len(), 1);
    let entry = &entries[0];
    assert_eq!(entry.kind, EntryKind::Video);
    assert_eq!(entry.url, url);
    assert!(!entry.media_id.is_empty());
    assert!(!entry.title.is_empty());
    // The `info` frame's full dict became the entry state, so `formats` is there for the
    // engine's §7.5 compaction and for the NFO hook.
    assert!(
        entry
            .state
            .get("formats")
            .is_some_and(serde_json::Value::is_array),
        "state = {}",
        entry.state
    );
}

#[tokio::test]
async fn a_real_file_url_download_writes_a_playable_file() {
    skip_unless_real!();
    let dir = TempDir::new().unwrap();
    let clip = make_clip(&dir);
    let out = dir.path().join("downloads");
    std::fs::create_dir_all(&out).unwrap();
    let url = Url::from_file_path(&clip).expect("a file url");

    let mut options = file_url_options();
    options.insert(
        "paths".to_owned(),
        json!({ "home": out, "temp": dir.path() }),
    );
    options.insert(
        "outtmpl".to_owned(),
        json!({ "default": "%(title)s.%(ext)s" }),
    );
    options.insert("format".to_owned(), json!("best"));
    options.insert("socket_timeout".to_owned(), json!(30));
    options.insert("ignore_no_formats_error".to_owned(), json!(true));

    let job = Job::download(ItemId::new().to_string(), url)
        .with_options(options)
        .with_download_root(&out)
        .with_policy(Policy {
            download_dir: out.clone(),
            temp_dir: dir.path().to_path_buf(),
            emit_progress_every_ms: 0,
            ..Policy::default()
        });

    let (sink, mut rx) = sink();
    let outcome = handle()
        .run(&job, &sink, &CancellationToken::new())
        .await
        .expect("a real download of a local file must succeed");
    drop(sink);

    let RunnerOutcome::Downloaded(result) = outcome else {
        panic!("expected a download outcome")
    };
    let relative = result
        .filename
        .as_ref()
        .expect("the download must report a filename");
    let written = out.join(relative.as_str());
    assert!(written.exists(), "{} was not written", written.display());
    let size = std::fs::metadata(&written).unwrap().len();
    assert!(size > 0);
    assert_eq!(result.size, Some(size), "the reported size must match disk");

    // The frame sequence the engine sees: `downloading` first, `postprocessing` once MoveFiles
    // starts, and at least one progress frame in between.
    let mut stages = Vec::new();
    let mut progress = 0;
    while let Some(msg) = rx.recv().await {
        match msg {
            ProgressMsg::Stage { stage, .. } => stages.push(stage),
            ProgressMsg::Progress { .. } => progress += 1,
            ProgressMsg::File { .. } => {}
        }
    }
    assert!(progress > 0, "no progress frames arrived");
    // `Stage::Preparing` is `YtdlpProvider::download`'s doing, not the runner's; driving the
    // handle directly starts at the first `progress` frame.
    assert_eq!(stages.first(), Some(&Stage::Downloading), "got {stages:?}");
    assert!(
        stages.contains(&Stage::Postprocessing),
        "MoveFiles must move the item to `postprocessing`: {stages:?}"
    );

    // "Playable" in the only sense a test can assert cheaply: ffprobe recognises a stream.
    if have("ffprobe") {
        let probe = Command::new("ffprobe")
            .args([
                "-v",
                "error",
                "-show_entries",
                "stream=codec_type",
                "-of",
                "csv=p=0",
            ])
            .arg(&written)
            .output()
            .unwrap();
        assert!(probe.status.success(), "ffprobe rejected the output file");
        let streams = String::from_utf8_lossy(&probe.stdout);
        assert!(
            streams.contains("video"),
            "the output has no video stream: {streams:?}"
        );
    }
}

#[tokio::test]
async fn a_real_selftest_reports_the_installed_yt_dlp_version() {
    if !have_ytdlp() {
        eprintln!("skipping: {} cannot import yt_dlp", python());
        return;
    }
    let h = handle();
    let (sink, _rx) = sink();
    let RunnerOutcome::Selftest(identity) = h
        .run(&Job::selftest("probe"), &sink, &CancellationToken::new())
        .await
        .expect("selftest")
    else {
        panic!("expected a selftest outcome")
    };
    let version = identity.yt_dlp.expect("a real yt-dlp reports a version");
    assert!(
        version.chars().next().is_some_and(char::is_numeric),
        "an implausible version string: {version:?}"
    );
    assert!(identity.python.is_some());
}
